resource "aws_s3_bucket" "frontend" {
  bucket = "mirza-${var.project_name}-frontend"
}

resource "aws_s3_bucket_website_configuration" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  index_document {
    suffix = "index.html"
  }
}

resource "aws_s3_bucket_public_access_block" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  block_public_acls       = false
  block_public_policy     = false
  ignore_public_acls      = false
  restrict_public_buckets = false
}

resource "aws_s3_bucket_policy" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "PublicReadGetObject"
        Effect    = "Allow"
        Principal = "*"
        Action    = "s3:GetObject"
        Resource  = "${aws_s3_bucket.frontend.arn}/*"
      }
    ]
  })

  depends_on = [aws_s3_bucket_public_access_block.frontend]
}

resource "aws_s3_object" "index_html" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "index.html"
  source        = "${path.root}/frontend/index.html"
  content_type  = "text/html"
  cache_control = "no-cache"
  source_hash   = filemd5("${path.root}/frontend/index.html")
}

resource "aws_s3_object" "style_css" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "style.css"
  source        = "${path.root}/frontend/style.css"
  content_type  = "text/css"
  cache_control = "no-cache"
  source_hash   = filemd5("${path.root}/frontend/style.css")
}

resource "aws_s3_object" "script_js" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "script.js"
  source        = "${path.root}/frontend/script.js"
  content_type  = "application/javascript"
  cache_control = "no-cache"
  source_hash   = filemd5("${path.root}/frontend/script.js")
}

# Generated by Terraform so the frontend never has stale IDs or URLs
resource "aws_s3_object" "config_js" {
  bucket        = aws_s3_bucket.frontend.id
  key           = "config.js"
  content_type  = "application/javascript"
  cache_control = "no-cache"

  content = "window.APP_CONFIG = ${jsonencode({
    cognitoDomain     = "https://${aws_cognito_user_pool_domain.expense_tracker_domain.domain}.auth.${var.aws_region}.amazoncognito.com"
    clientId          = aws_cognito_user_pool_client.expense_tracker_client.id
    redirectUri       = "https://${aws_cloudfront_distribution.frontend.domain_name}"
    logoutRedirectUri = "https://${aws_cloudfront_distribution.frontend.domain_name}"
    apiUrl            = aws_apigatewayv2_api.expense_tracker_api.api_endpoint
  })};"
}

output "website_url" {
  value = "http://${aws_s3_bucket_website_configuration.frontend.website_endpoint}"
}